### ISSUE TITLE
Error when trying to create the island

### ISSUE THREAD

**Issue by kaio200816** [BeeAZ-pm-pl/ASkyBlock#2]
https://crash.pmmp.io/view/9105765

**Comment by BeeAZ-pm-pl** [comment]
it can't be like that, i tested again, it's no problem!

**Comment by GabBiswajit** [comment]
#3 Is A Temporary Salution Try It @kaio200816.
This Poblam Happened Because Your Island World.

**Comment by BeeAZ-pm-pl** [comment]
Please install the MultiWorld plugin if you use this plugin's default world !

**Comment by BeeAZ-pm-pl** [comment]
https://poggit.pmmp.io/p/MultiWorld/2.1.0
